### ISSUE TITLE
Tell me how to run this...

### ISSUE THREAD

**Issue by sealabr** [yotam180/WhatsappAPI#32]
please, explain me how to run in my browser

thanks

**Comment by yotam180** [comment]
Hey, and thanks for the interest.
I'm still heavily working on this one, for now, it is in no way really usable.
I'll let you know when I have a truly working version, alright? 

Yotam.

**Comment by sealabr** [comment]
okay! thanks 👍

**Comment by yotam180** [comment]
You can subscribe to #33 and I'll let you know there when something is ready :)
