### ISSUE TITLE
how to send message to unkown

### ISSUE THREAD

**Issue by itclubonline** [yotam180/WhatsappAPI#36]
I am intended to send message to uknon no, which is not in my contact list. Could you please guide us how to handle this.

 
I want to send message to member in group but not in my contact list. If I manually click on the no listed in group i am able to send message. but how to do the same with js.

**Comment by yotam180** [comment]
Unfortunately, my this API terms of use state:
> YOU WILL NOT SEND MESSAGE TO PEOPLE THAT ARE NOT ON YOUR CONTACT LIST

What is your scenario? What do you want to send to people who are not on your contact list? If they have messaged you before, they automatically are added to your WhatsApp contact list, so you do not have to worry about that.

**Comment by itclubonline** [comment]
i want to send message to member in group but not in my contact list.
I am able to send message to them through clicking on contact in group list.

**Comment by itclubonline** [comment]
I want to send message to member in group but not in my contact list. If I manually click on the no listed in group i am able to send message. but how to do the same with js.

**Comment by itclubonline** [comment]
I want to send message to member in group but not in my contact list. If I manually click on the no listed in group i am able to send message. but how to do the same with js.

**Comment by itclubonline** [comment]
I want to send message to member in group but not in my contact list. If I manually click on the no listed in group i am able to send message. but how to do the same with js.

**Comment by itclubonline** [comment]
I want to send message to member in group but not in my contact list. If I manually click on the no listed in group i am able to send message. but how to do the same with js.

**Comment by yotam180** [comment]
You should be able to grab the user by `Core.chat("<USER_PHONE_INCLUDING_COUNTRY_PREFIX>@c.us")`.

Then on the returned object you can do:

```
function send(number, message) {
    var user = Core.chat(number + "@c.us");
    user.sendMessage(message);
}
```

**Comment by BaukaKZ** [comment]
var id = new window.Store.UserConstructor("123123123@c.us");
Store.Chat.find(id).then(function(chat) {
chat.markComposing();
chat.sendMessage("....");
});
