### ISSUE TITLE
Profile Image Download with API [HELP PLEASE]

### ISSUE THREAD

**Issue by whatsappapi** [yotam180/WhatsappAPI#37]
Hi, i want to download or post to my webservice user profile pic. Can you help me pls?

My example code:

```
for (i = number; i < number2; i++) {
    Store.ProfilePicThumb.find(i+ '@c.us').then(function(r){
        var image = r.img;
        if (image === null) {}
        else if (image === undefined) {} 
        else {
            console.log(image);
        }	
    });
}
```

@yotam180

**Comment by yotam180** [comment]
Yes, I can.

What you receive back as `image` is a string consisting the URL (for example): 
```
https://dyn.web.whatsapp.com/pp?e=https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F24<censored>14_174<censored>77893_<censored>_n.jpg%3Foe%3D5AD0D4B7%26oh%3D5e<censored>f4a6cfb88d97914f71ad35&t=s&u=97<censored>36%40c.us&i=151<censored>20
```

Now what you have to do is just to take the inner URL part (the string is built as a URL, which's one of its query string parameters is another URL).

You have to take this:
```
https%3A%2F%2Fpps.whatsapp.net%2Fv%2Ft61.11540-24%2F24<censored>14_174<censored>77893_<censored>_n.jpg%3Foe%3D5AD0D4B7%26oh%3D5e<censored>f4a6cfb88d97914f71ad35
```

From some slight testing (I'm not guaranteeing this to work 100% as I have not seen much variety of URLs generated by WhatsApp Web that way), I assume you can just extract the inner URL like that:
```
var url = image.match(/https\%3A\%2F\%2F.+?\&/g)[0];
```

This regex will search starting at the `https://` of the URL and ends at the `&` which does not belong to the URL anymore. Then you can just url-decode it:
```
var decoded = decodeURIComponent(url);
```

And that's a download link for the image. You can now send it to your web service and download the actual image from there (you cannot download it straight from your Javascript as the WhatsApp server does not add a CORS header for the image).

Yotam.

**Comment by whatsappapi** [comment]
@yotam180 I tried send to my api but everytime xhr error. I cant post request to my server because of whatsapp web. Can you please give me example? Thank you.

**Comment by yotam180** [comment]
Yes. As WhatsApp Web forbids HTTP requests, we provide an alternative networking gate.

We defined a function named `$ajax` (similarly to jQuery's `$.ajax`). You can use it like that:

```
$ajax({
    url: "<THE_URL>",
    type: "GET" or "POST" or "PUT" or whatever you like,
    data: {
        Every get/post parameter you want to send
    },
    success: function(content) { }
    error: function(a, b, c) { }
});
```

This will make an asynchronous web request.
