### ISSUE TITLE
Store is not defined

### ISSUE THREAD

**Issue by BaukaKZ** [yotam180/WhatsappAPI#54]
Store is not defined 
will this problem be solved ?

**Comment by yurik44** [comment]
Same problem here.

**Comment by BaukaKZ** [comment]
> Same problem here.

если найдешь решение отпишись пожалуйста !!!

**Comment by yurik44** [comment]
> если найдешь решение отпишись пожалуйста !!!

WhatsApp changed "id" to "i", just it.

**Comment by yurik44** [comment]
> > Same problem here.
> 
> если найдешь решение отпишись пожалуйста !!!

					```
//webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, 'parasite');
webpackJsonp([], {'parasite': (x, y, z) => getStore(z)}, ['parasite']);

{id: "SendTextMsgToChat",conditions: (module) => (module.sendTextMsgToChat) ? module.sendTextMsgToChat : null},
{id: "ChatClass", conditions: (module) => (module.default && module.default.prototype && module.default.prototype.Collection !== undefined && module.default.prototype.Collection === "Chat") ? module : null }
```

**Comment by BaukaKZ** [comment]
Спасибо большое !!!! целую тебя в почки

сб, 1 июн. 2019 г. в 10:30, yurik44 <notifications@github.com>:

**Comment by msin87** [comment]
https://github.com/Zibri/WhatsAppWebApi/blob/master/zstore.js

**Comment by yotam180** [comment]
@msin87 Thank you for pointing that out. I'll check that code and integrate the fix to the API as soon as possible.

**Comment by msin87** [comment]
> @msin87 Thank you for pointing that out. I'll check that code and integrate the fix to the API as soon as possible.

update: 
I replaced your method of getting the Store with a method from another project:
https://github.com/mukulhase/WebWhatsapp-Wrapper/blob/master/webwhatsapi/js/wapi.js 
Just replace your method and you will get advanced functionality. You can send messages to people without adding them to your contacts by WAPI.sendMessageToID(...);
Enjoy, and update your project pls :)

**Comment by msin87** [comment]
add: 
 In the group chat, I clicked on the joined member who is not in my contacts, then a dialog box with him opened. Then I closed the window by pressing Escape on the keyboard, and called sending by id. It is necessary to trace where and how the new user object is added, and manually create and add it. Perhaps this object is created on the server side.

**Comment by yotam180** [comment]
As for my understanding, if that user had messaged you, the user object would've been available to you; That's the optimal situation in my opinion.

I don't wish to support messaging specific users if they're not a contact of ours, or we do not share a message history with them. That's just a modest way to prevent spam-bots, etc...

I hope you see my point, but, if I misunderstood your request, please correct me.

**Comment by msin87** [comment]
My solution:

> I finally figured out how to make the function
> `Store.Chat.find (USERID)` could find a user who is not in contacts.
> `USERID` - in the format `'123456789@c.us'`
> You must add a chat with the user through the API.
> Sequence:
> 1) `Store.Chat._staleCollection = true;`
> Without setting this parameter to true, the API will think that the new chat should not be added to the collection.
> 2) ` Store.Chat._serverQuery.call(Store.Chat, 'FIND', Store.Contact.find(USERID)._value.__x_id);`
> (you can call` Store.Chat.find(USERID)` for checking)
> 3) `Store.Chat._staleCollection = false;`
> And finally send the message:
> `Store.SendTextMsgToChat(USERID, message_text);`
> **Please update wapi.js** by adding such excellent functionality there.

https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/662#issuecomment-502250183
